### ISSUE TITLE
Iceberg goes into a loop sometimes

### ISSUE THREAD

**Issue by activ** [dreulavelle/iceberg#129] opened 2024-01-15 09:36 UTC
Not entirely sure what causes the loop, but here is a log snippet showing the loop. It will keep going like that forever.
I have already redone the config and deleted the pal files, but it comes back anyway.

```
Iceberg  | [2024-01-15 09:06:41 | DEBUG] <realdebrid._determine_best_stream> - No cached release found for Doctor Who S07
Iceberg  | [2024-01-15 09:06:43 | DEBUG] <orionoid._scrape_item> - Found 3 streams for Doctor Who S07
Iceberg  | [2024-01-15 09:06:43 | DEBUG] <realdebrid._determine_best_stream> - No cached release found for Doctor Who S08
Iceberg  | [2024-01-15 09:06:44 | DEBUG] <orionoid._scrape_item> - Found 2 streams for Doctor Who S08
Iceberg  | [2024-01-15 09:06:44 | DEBUG] <realdebrid._determine_best_stream> - No cached release found for Doctor Who S09
Iceberg  | [2024-01-15 09:06:45 | DEBUG] <orionoid._scrape_item> - Found 7 streams for Doctor Who S09
Iceberg  | [2024-01-15 09:06:46 | DEBUG] <orionoid._scrape_item> - Could not find streams for Doctor Who S10
Iceberg  | [2024-01-15 09:06:46 | DEBUG] <realdebrid._determine_best_stream> - No cached release found for Doctor Who S11
Iceberg  | [2024-01-15 09:06:47 | DEBUG] <orionoid._scrape_item> - Found 5 streams for Doctor Who S11
Iceberg  | [2024-01-15 09:06:48 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:48 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:49 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:49 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:50 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:50 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:50 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:51 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:51 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:52 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:52 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:52 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:53 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:53 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:54 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:54 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:55 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:55 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:56 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:56 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
Iceberg  | [2024-01-15 09:06:56 | DEBUG] <realdebrid._determine_best_stream> - Found cached release for Doctor Who S12
Iceberg  | [2024-01-15 09:06:56 | DEBUG] <realdebrid._is_downloaded> - Torrent for Doctor Who S12 already downloaded
```

**Comment by dreulavelle** [comment] 2024-01-16 21:23
Duplicate of #127 

This has been solved in GH-82

**Closed by dreulavelle** 2024-01-16 21:23 UTC
